### ISSUE TITLE
mediaplayer-app does not have a maintainer

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/mediaplayer-app#2]
No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.

The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):

* Triaging bugs
* Fixing bugs
* Vetting and implementing enhancement requests
* Corresponding with the UBports project regarding the app's progress
* Requesting bounties be posted for the app
* Watching *a lot* of media

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/mediaplayer-app/-/issues/2

Sorry for your inconvenience.
