### ISSUE TITLE
mediaplayer-app has no subtitle suppport

### ISSUE THREAD

**Issue by lazmol** [ubports/mediaplayer-app#3]
Subtitle suppport would be really grand!

**Comment by Flohack74** [comment]
How are subtitles stored with various media, isn't that very format-specific?

**Comment by lazmol** [comment]
Sorry, I am not an expert on subtitle formats but I think the most wide spread one is srt, so the support of that would already fullfill my occasional needs when I'd like to watch something with subtitles.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/mediaplayer-app/-/issues/3

Sorry for your inconvenience.
