### ISSUE TITLE
E5: Media Player cannot playback recorded videos anymore

### ISSUE THREAD

**Issue by Flohack74** [ubports/mediaplayer-app#5]
For some reason the possibility to playback videos on my E5 is broken. Videos are fine on the PC when I copy them there. The internal player on the phone complains about unsupported format however...

This also applies to older videos from 2016 so for sure its not a bug of the camera part.

**Comment by Flohack74** [comment]
I am afraid there is no fix available currently.

**Comment by vokaliz** [comment]
But the video player worked propertly and everything was fine. Just stopped working one day. It's too bad, really not enough player. Thanks for responding!

**Comment by doniks** [comment]
could it be its just missing some gstreamer plugins?

**Comment by vokaliz** [comment]
![9494379](https://user-images.githubusercontent.com/39481201/40309629-cef9e0de-5d12-11e8-8c5d-593a3be79494.png)

**Comment by Flohack74** [comment]
You can try whatever you want, its a community project ;)

**Comment by vokaliz** [comment]
I wouldn't want to try different ways if the community doesn't have enough experience to solve this problem.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/mediaplayer-app/-/issues/5

Sorry for your inconvenience.
