### ISSUE TITLE
Mediaplayer cannot playback mp4 format

### ISSUE THREAD

**Issue by Flohack74** [ubports/mediaplayer-app#6]
Dont know if that affects all mp4 subformats but this should really work without issue for all.

**Comment by doniks** [comment]
Can't play bib buck bunny on Nexus 7 deb either
http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi

**Comment by Anne017** [comment]
Also affected by this bug on FP2, OTA-8, stable channel

**Comment by Anne017** [comment]
Not affected anymore by this bug on FP2, OTA-10, stable channel
[https://www.sample-videos.com/video123/mp4/240/big_buck_bunny_240p_30mb.mp4](https://www.sample-videos.com/video123/mp4/240/big_buck_bunny_240p_30mb.mp4
)

However, I cannot play .avi files
[http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi](http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/mediaplayer-app/-/issues/6

Sorry for your inconvenience.
