### ISSUE TITLE
Support for mp3 playlist format .m3u

### ISSUE THREAD

**Issue by Flohack74** [ubports/mediaplayer-app#7]
Often I copy a folder with songs that have been recorded from a livestream, and my grabber automatically creates an m3u file for playing them in the correct order (otherwise the fadein/fadeout part sounds wonky). While mediaplayer supports playlists it ignores any m3u file. It would be cool to have a solution for that.

**Comment by Flohack74** [comment]
@ChloeWolfieGirl :)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/mediaplayer-app/-/issues/7

Sorry for your inconvenience.
