### ISSUE TITLE
Store position for better audiobook support

### ISSUE THREAD

**Issue by ghost** [ubports/mediaplayer-app#8]
Current Version:
2.5.1019

Position of audio file should be stored also after restart of App and/ or Phone.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/mediaplayer-app/-/issues/8

Sorry for your inconvenience.
